spring:
  h2:
      console:
        enabled: true
        path: /h2-console

  datasource:
    url : jdbc:h2:mem:gildonglog;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

gichang:
  jwt-key: "H9xWQ2HuOWfU6HB08WaJRXmBP9A1cuRUwI577GHRpCE"
