spring:
  h2:
      console:
        enabled: true
        path: /h2-console
  datasource:
    url : jdbc:h2:mem:gildonglog;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5