### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email" : "parkgc0504@gmail.com",
  "password" : "dpqls"
}

### 인증 페이지 요청

GET http://localhost:8080/foo
Content-Type: application/json
Cookie: SESSION =f7bb89bb-acbc-4bc2-9032-116365e56f06
### Authorization: fccaef27-a87a-4eb9-8701-a4ed17f2169c
